
export interface CountryCode {
  name: string;
  code: string;
  flag: string;
  digits: string;
}

export const countryCodes: CountryCode[] = [
  { name: 'United States', code: '+1', flag: '🇺🇸', digits: '10' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', digits: '10' },
  { name: 'India', code: '+91', flag: '🇮🇳', digits: '10' },
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', digits: '9' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', digits: '9' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', digits: '9' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', digits: '6' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', digits: '9' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', digits: '10' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', digits: '8' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', digits: '9' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', digits: '9' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', digits: '9' },
  { name: 'Bahamas', code: '+1-242', flag: '🇧🇸', digits: '10' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', digits: '8' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', digits: '10' },
  { name: 'Barbados', code: '+1-246', flag: '🇧🇧', digits: '10' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', digits: '9' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', digits: '9' },
  { name: 'Belize', code: '+501', flag: '🇧🇿', digits: '7' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', digits: '8' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', digits: '8' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', digits: '8' },
  { name: 'Bosnia & Herzegovina', code: '+387', flag: '🇧🇦', digits: '8' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', digits: '8' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', digits: '10-11' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳', digits: '7' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', digits: '7-9' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', digits: '8' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', digits: '8' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', digits: '9' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', digits: '9' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', digits: '10' },
  { name: 'Cape Verde', code: '+238', flag: '🇨🇻', digits: '7' },
  { name: 'Central African Rep.', code: '+236', flag: '🇨🇫', digits: '8' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', digits: '8' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', digits: '9' },
  { name: 'China', code: '+86', flag: '🇨🇳', digits: '11' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', digits: '10' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', digits: '8' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', digits: '8-9' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺', digits: '8' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', digits: '8' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', digits: '9' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', digits: '8' },
  { name: 'Dominica', code: '+1-767', flag: '🇩🇲', digits: '10' },
  { name: 'Dominican Republic', code: '+1-809', flag: '🇩🇴', digits: '10' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', digits: '9' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', digits: '10' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', digits: '8' },
  { name: 'Eritrea', code: '+291', flag: '🇪🇷', digits: '7' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', digits: '7-8' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', digits: '9' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', digits: '7' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', digits: '9' },
  { name: 'France', code: '+33', flag: '🇫🇷', digits: '9' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', digits: '7' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', digits: '7' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', digits: '9' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', digits: '10-11' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', digits: '9' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', digits: '10' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', digits: '8' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', digits: '9' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', digits: '7' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', digits: '8' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', digits: '8' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', digits: '9' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', digits: '7' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', digits: '9-11' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', digits: '10' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', digits: '10' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', digits: '9' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', digits: '9' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', digits: '9-10' },
  { name: 'Jamaica', code: '+1-876', flag: '🇯🇲', digits: '10' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', digits: '10' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', digits: '9' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', digits: '10' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', digits: '9' },
  { name: 'Korea (South)', code: '+82', flag: '🇰🇷', digits: '9-10' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', digits: '8' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', digits: '9' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', digits: '9' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', digits: '8' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', digits: '7-8' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', digits: '7-8' },
  { name: 'Libya', code: '+218', flag: '🇱🇾', digits: '9' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', digits: '7' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', digits: '8' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', digits: '9' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', digits: '9' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', digits: '9' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', digits: '9-10' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', digits: '7' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', digits: '8' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', digits: '8' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', digits: '10' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', digits: '8' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', digits: '8-9' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', digits: '8' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', digits: '8' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', digits: '9' },
  { name: 'Myanmar', code: '+95', flag: '🇲🇲', digits: '8-9' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', digits: '8' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', digits: '10' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', digits: '9' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', digits: '8-9' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', digits: '8' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', digits: '8' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', digits: '10' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', digits: '8' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', digits: '8' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', digits: '10' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', digits: '8' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', digits: '8' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', digits: '9' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', digits: '9' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', digits: '10' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', digits: '9' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', digits: '9' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', digits: '8' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', digits: '9' },
  { name: 'Russia', code: '+7', flag: '🇷🇺', digits: '10' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', digits: '9' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', digits: '9' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', digits: '9' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', digits: '8-9' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', digits: '7' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', digits: '8' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', digits: '8' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', digits: '9' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', digits: '8' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', digits: '9' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', digits: '9' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', digits: '9' },
  { name: 'Sudan', code: '+249', flag: '🇸🇩', digits: '9' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', digits: '9' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', digits: '9' },
  { name: 'Syria', code: '+963', flag: '🇸🇾', digits: '9' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', digits: '9' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', digits: '9' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', digits: '9' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', digits: '9' },
  { name: 'Togo', code: '+228', flag: '🇹🇬', digits: '8' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴', digits: '5' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', digits: '8' },
  { 'name': 'Turkey', 'code': '+90', 'flag': '🇹🇷', 'digits': '10' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', digits: '8' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', digits: '9' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', digits: '9' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', digits: '9' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', digits: '8' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', digits: '9' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', digits: '10' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', digits: '9-10' },
  { name: 'Yemen', code: '+967', flag: '🇾🇪', digits: '9' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', digits: '9' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', digits: '9' },
];
